### ISSUE TITLE
Output console opening whenever it detects an error

### ISSUE THREAD

**Issue by andmm** [bmewburn/intelephense#40] opened 2017-06-27 21:55 UTC
Don't know why this is happening but the output panel keeps opening for me whenever it detects an error on the php code making this extension unusable for me.  I tried finding an option for this behavior but I couldn't find it. 

![error](https://user-images.githubusercontent.com/4256677/27611815-12845934-5b6a-11e7-9e16-bd385e56c405.png)

How can I disable this? Thanks.

**Comment by bmewburn** [comment] 2017-07-03 14:38
Thanks for reporting. The cause of the error has been resolved in v0.7.2. It must be the default behaviour of the editor to open the output on errors. I would imagine there's a setting somewhere for that, I'm unsure where it is though.

**Closed by bmewburn** 2017-07-03 14:38 UTC

**Comment by andmm** [comment] 2017-07-06 14:17
Still happening on 0.7.2.

**Comment by bmewburn** [comment] 2017-07-06 19:00
Can you post the error?
