### ISSUE TITLE
Correct settings to get Intelliphense to highlight/suggest HTMLtags

### ISSUE THREAD

**Issue by mateus-so** [bmewburn/intelephense#134] opened 2018-05-02 16:01 UTC
Hello guys, how are you doing?

So, I was wondering what are the correct settings I gotta use, so I can achieve the result attached:
![33985887-f7a9d89c-e10f-11e7-8e6b-f5844e630149 1](https://user-images.githubusercontent.com/34314810/39534760-b56dd8d2-4e08-11e8-96f2-2142dc1068b1.gif)

As I said on the title, all I want is tag highlight (pairing) and suggestions/auto-complete to HTML, inside PHP files. It would be great to get indent too, but it's not my priority. Thanks!

**Comment by onetrev** [comment] 2018-07-26 06:54
Duplicate of [this issue](https://github.com/bmewburn/intelephense/issues/106) I believe. There was some disagreement on whether this could be replicated, but lots of others seemed to have the same issue as you. Either way, not sure @bmewburn is active anymore.

You can follow [this issue](https://github.com/Microsoft/vscode/issues/1751) which would allow finally for various mixed language support in VS Code, including in [PHP Intellisense](https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-intellisense).

**Comment by bmewburn** [comment] 2019-02-26 02:25
bmewburn/vscode-intelephense#239

**Closed by bmewburn** 2019-02-26 02:25 UTC
